- name: Install required packages for Docker
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes
  become: yes

- name: Add Docker's official GPG key
  shell: |
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.gpg > /dev/null
    sudo chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  become: yes

- name: Add Docker repository
  shell: |
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list
  become: yes

- name: Update APT cache after adding Docker repo
  apt:
    update_cache: yes
  become: yes

- name: Install Docker and dependencies
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: yes

- name: Ensure Docker service is running
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes

- name: Add "{{ username }}" to the docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
  become: yes
