- name: Install dependencies for Homebrew
  apt:
    name:
      - build-essential
      - procps
      - curl
      - file
      - git
    update_cache: yes
  become: yes

- name: Check if Homebrew is installed
  ansible.builtin.stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew
  register: brew_installed

- name: Download and run the Homebrew installer
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/brew
  become: false
  when: not brew_installed.stat.exists

- name: Add Homebrew to zshrc
  ansible.builtin.lineinfile:
    path: "/home/{{ username }}/.zshrc"
    line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
    create: yes
    state: present

- name: Ensure brew command is available in PATH
  ansible.builtin.lineinfile:
    path: "/home/{{ username }}/.zshrc"
    line: 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"'
    create: yes
    state: present

- name: Reload shell environment for Homebrew
  shell: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"
  args:
    executable: /bin/bash

- name: Install Flux and other necessary tools via Homebrew
  community.general.homebrew:
    name:
      - kubectl
      - kubectx
      - fzf
      - terraform
      - git-delta
      - kubecolor
      - helm
      - yq
      - jq
      - kustomize
      - fluxcd/tap/flux
      - kyverno
      - gh
      - python3
    state: present
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"
  become: false

- name: Install Packer from HashiCorp tap
  community.general.homebrew:
    name: hashicorp/tap/packer
    state: present
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"
  become: false
