# https://megalinter.io/latest/configration/
ENABLE_LINTERS:
  - YAML_YAMLLINT
  - MARKDOWN_MARKDOWNLINT
  - ANSIBLE_ANSIBLE_LINT
REPORT_OUTPUT_FOLDER: none
SHOW_SKIPPED_LINTERS: false
REPORTERS_MARKDWON_TYPE: simple

MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: false

ANSIBLE_DIRECTORY: .
EXCLUDED_DIRCTORIES: .git